CREATE TABLE Parent (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  caption VARCHAR (64) NOT NULL
);

CREATE TABLE Child (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  caption VARCHAR (64) NOT NULL,
  parentId INTEGER NOT NULL,
  FOREIGN KEY (parentId)
    REFERENCES Parent(id)
);