DROP TABLE IF EXISTS Products;

CREATE TABLE Products (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  productName VARCHAR (256) NOT NULL,
  description VARCHAR (256) NOT NULL
);

CREATE TABLE Users (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  login VARCHAR (256) UNIQUE NOT NULL,
  password VARCHAR (256) NOT NULL,
  email VARCHAR (256) UNIQUE NOT NULL
);

-- SET DATABASE TRANSACTION CONTROL MVCC;